[workspace]
members = [
	"cli",
	"consensus/pow",
	"primitives",
	"primitives/account",
	"pallets/rewards",
	"pallets/difficulty",
	"rpc",
	"runtime",
	"utils/subkey",
]
[profile.release]
panic = "unwind"